### ISSUE TITLE
Full command is always displayed instead of only process name

### ISSUE THREAD

**Issue by jathek** [trystan2k/zsh-tab-title#23]
Using https://github.com/trystan2k/zsh-tab-title/commit/44f5220b560ff13bb75d090b187f7cad8849e9d4 and `ZSH_TAB_TITLE_CONCAT_FOLDER_PROCESS=true`, the full command is always displayed instead of just the process name.

**Comment by trystan2k** [comment]
Hi @jathek,

I will take a look. Do you mind give me more details ? What OS are you using (Linux, Mac, Windows - WSL?) ? What terminal are you using (Iterm, CMD, Git Bash) ? Are you using Bash, ZSH, Fish ?

Thanks

**Comment by jathek** [comment]
OS: Microsoft Windows 10 [Version 10.0.19045.3930]
Terminal: Windows Terminal Preview 1.20.10572.0
Git Bash: 2.44.0.windows.1
Zsh: 5.9 (x86_64-pc-msys)

**Comment by levaspb** [comment]
same here
OS: MacOS 14.4
Zsh: 5.9 (x86_64-apple-darwin23.0)

**Comment by trystan2k** [comment]
Hi @jathek and @levaspb,

So sorry for the late reply.

I have pushed some changes, and it should be working as expected now.

When the is set to **false** (default value) it is only shown the command been executed.
Example: You can see that the tile show: `ls -al`
<img width="464" alt="image" src="https://github.com/trystan2k/zsh-tab-title/assets/447294/0458a230-e569-4bdb-b335-b0c8d6c8e893">


When it is set to **true** then the current folder is concatenated to the command being executed
Example: You can see that the title show: `trystan2k---zsh-tab-title:ls -al`
<img width="475" alt="image" src="https://github.com/trystan2k/zsh-tab-title/assets/447294/02eb7853-2c8f-4712-bfd2-122bb64df4b8">

**IMPORTANT**
I have changed the default branch of the repository (from master to main) so to get this change, please uninstall the plugin and install it again.

Please let me know if this fixes the issue you had before.

Thank you !

**Comment by jathek** [comment]
I think it's still not working based on this screenshot. If I understand the feature correctly, it should only show "test:sleep". Instead it shows "test:sleep 5".
![image](https://github.com/trystan2k/zsh-tab-title/assets/692914/b0deaa62-a0c2-4cf4-a6cb-659dcdbe79f6)

I believe I'm on the latest commit on main:
![image](https://github.com/trystan2k/zsh-tab-title/assets/692914/68c2dcbc-2f61-415d-a6eb-4a6102718afe)

**Comment by trystan2k** [comment]
Hi @jathek 

Ok, now I got what you were talking about. The issue was that it was setting terminal title and tab title with different values and in your case, you were only seen the incorrect one.

I have changed, so now both follow the setting of full command:
<img width="1211" alt="image" src="https://github.com/trystan2k/zsh-tab-title/assets/447294/c4309331-0932-4c8e-88f1-bc164dd81727">

Can you please update to the last commit (v3.1.0), try again and let me know if you see it ok now ?

**Comment by jathek** [comment]
works now
![image](https://github.com/trystan2k/zsh-tab-title/assets/692914/8f62b91b-4a31-4f90-a384-dc1979462d84)

**Comment by trystan2k** [comment]
Great ! I will close the issue then. Thanks for reporting it !
